### ISSUE TITLE
Unable to run correctly

### ISSUE THREAD

**Issue by A-kafka** [CsurillaK/HybridPositionForceControl#1]
Thank you for sharing, but why is the main. m file blank when I run it? My MATLAB version is 2023b

**Comment by CsurillaK** [comment]
Could you please elaborate on "blank main.m file"? Are you getting any specific error message?

**Comment by A-kafka** [comment]
> Could you please elaborate on "blank main.m file"? Are you getting any specific error message?
It's my problem, I didn't install the GUI toolbox. What a great learning project! It helps me with the problem of intuitive learning ability control without equipment. Thank you very much.

**Comment by CsurillaK** [comment]
Thank you for your comment! I will find a better way to let users know about this dependency later today.

**Comment by CsurillaK** [comment]
Added check to main.m, user should now be notified of missing GUI Layout Toolbox.
